# Generated by Django 6.0.3 on 2026-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma separated sizes (e.g., 39, 40, 41 or S, M, L)', max_length=255),
        ),
    ]
