# Generated by Django 6.0.3 on 2026-03-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma separated colors (e.g., Black, White, Red)', max_length=255),
        ),
    ]
